### ISSUE TITLE
Add some articles about what it's like to work in Quant

### ISSUE THREAD

**Issue by mikinty** [mikinty/Trading-Interview-Questions#6]
https://blog.headlandstech.com/2017/08/03/quantitative-trading-summary/

**Comment by DiegoGarciaPadilla** [comment]
[What Is Quantitative Trading? Definition, Examples, and Profit](https://www.investopedia.com/terms/q/quantitative-trading.asp)

**Comment by mikinty** [comment]
https://www.thewallstreetquants.com/cone1-firm-list

**Comment by mikinty** [comment]
Done in 039976e
